### ISSUE TITLE
ERROR SOFTWARE

### ISSUE THREAD

**Issue by sandeeppoudel2054** [thulobilling/thulobilling#16]
IN WEB app
Error
1.When we mouse hover in log out area logout text is not visible .
Effect: user directly logout  unknownly
2. setting button is not work
3.Help and support is not work in send button
4. Guide menu video is not full area 
5.In guide tips 03 how to generate sale bills?  04 how to add purchase bill if we  Click open video in youtube new tab
6.In guide tips 05 06 07 08 if we click video play and pause happen
7.in Fiscal year menu .if add fiscal year or add name value is store in name location number is store in name location.
8.in business menu pan number accept alphabet value
9.in sales menu add sales tax button is not work.
10. In sales menu save and print button is not work
11. In purchase  menu save and print button is not work
12. In purchase  menu export is not work
13. in report menu North east corner button doest not give actual meaning this not need

**Comment by samirpokharel** [comment]
soved
