### ISSUE TITLE
S/N is confusing: It's may be an issue. 

### ISSUE THREAD

**Issue by nandalalsun** [thulobilling/thulobilling#69]
I don't know why the S/N is not in order. Sometimes it shows correctly but not all the time. 

![Screen Shot 2021-04-16 at 4 53 33 PM](https://user-images.githubusercontent.com/31072231/115016668-1c014500-9ed5-11eb-9d3b-7de5eef9946f.png)

**Comment by samirpokharel** [comment]
aba hudina hola
clear huna bankao xa
kasto sitattion ma teseto huncha ???
